### ISSUE TITLE
Multiple data races detected by TSAN (clang-11)

### ISSUE THREAD

**Issue by vrasidas-at-improbable** [taskflow/taskflow#292] opened 2021-03-01 14:42 UTC
**Describe the bug**
We are using taskflow in one of our projects and as part of our CI we run TSAN. Since integrating with taskflow TSAN has been detecting numerous data races. The minimal example below, raises anywhere between 16 to 40+ data races when running under TSAN.

**Repro**
Minimal repro (replicating the simple example from https://taskflow.github.io/taskflow/A1ForEach.html#A1IteratorBasedParallelFor):

```
#include <taskflow/taskflow.hpp>
#include <vector>

int main(int argc, char **argv){
  std::vector<int> vec = {1, 2, 3, 4, 5};
  tf::Executor executor{4};

  tf::Taskflow taskflow{};

  taskflow.for_each(vec.begin(), vec.end(), [&](int i) { std::cout << i << std::endl; });
  executor.run(taskflow).wait();

  return 0;
}
```
Compile with: 
```
clang++-11 -fsanitize=thread -I<taskflow_path> minimal_repro.cpp -o minimal_repro.x -std=c++17
```
Error log:
[tsan_error.log](https://github.com/taskflow/taskflow/files/6062344/tsan_error.log)

**Desktop:**
* OS: Ubuntu 18.04
* Compiler: clang-11 
* taskflow-version: 2.7.0

**Comment by tsung-wei-huang** [comment] 2021-03-02 16:55
@vrasidas-at-improbable I will look into this - but I believe this is a false alarm which would never happen based on our application-level scheduling algorithm.

**Comment by vrasidas-at-improbable** [comment] 2021-03-02 20:08
@tsung-wei-huang  thank you very much for picking this up. Please let us know as soon as you have any updates.

**Comment by tsung-wei-huang** [comment] 2021-09-02 23:26
@vrasidas-at-improbable  I believe this has been solved in the newest master branch. Workflow has added Thread Sanitizer to the integration check. The complaints of data race are primarily caused by weak memory reordering in C++. This fix will be integrated in the next release 3.4.

**Closed by tsung-wei-huang** 2021-09-02 23:26 UTC
Labels: question

**Comment by vrasidas-at-improbable** [comment] 2021-12-02 16:40
@tsung-wei-huang Thank you very much for looking further into this and fixing the issue. Do you have any timeline when will this fix be available in a release?

**Comment by tsung-wei-huang** [comment] 2021-12-02 17:54
The current master branch has this issue fixed - and I plan to have another release early next year to include another important tasking algorithm, pipeline.

**Comment by vrasidas-at-improbable** [comment] 2021-12-03 09:43
Great! Thank you very much for letting me know.
