### ISSUE TITLE
Memory leak detected by CppUTest in simple Taskflow example for v3.3.0+

### ISSUE THREAD

**Issue by coder137** [taskflow/taskflow#450] opened 2022-11-30 11:17 UTC
**Describe the bug**
CppUTest finds a memory leak

```
 error: Failure in TEST(TaskStateTestGroup, TestTask)
        Memory leak(s) found.
Alloc num (7) Leak size: 65584 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <0x5612712bdfc0> Content:
```

**To Reproduce**
1. Setup a simple project with CppUTest (memory leak detection on)
2. Compile a simple example test case
```cpp
TEST(TaskStateTestGroup, TestTask) {
  tf::Taskflow taskflow;
  taskflow.emplace([]() { UT_PRINT("Hello World"); });

  tf::Executor executor(1);
  executor.run(taskflow).wait();
}
```
Commenting out the executor also causes a memory leak error
```cpp
TEST(TaskStateTestGroup, TestTask) {
  tf::Taskflow taskflow;
  taskflow.emplace([]() { UT_PRINT("Hello World"); });

  // tf::Executor executor(1);
  // executor.run(taskflow).wait();
}
```
3. Test fails, error message pasted above

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu 20.04) on Windows 10

**Additional context**
1. I do not see this above error message in v3.2.0, only v3.3.0 onwards
This is also replicated on the current master branch

2. CppUTest does flag certain false positives (such as static global variables as memory leaks etc).

**Comment by tsung-wei-huang** [comment] 2022-11-30 18:17
@coder137 would you please try the current master branch again? Please let me know if the problem still exists in the current master branch.

**Comment by coder137** [comment] 2022-11-30 21:21
Hi @tsung-wei-huang,
I still see this error with the current master branch (Current commit: 3c97c903180ccf1a882cf9afd75509c48182f315)

Re-pasting
```
Failure in TEST(TaskStateTestGroup, TestTask)
        Memory leak(s) found.
Alloc num (7) Leak size: 65584 Allocated at: <unknown> and line: 0. Type: "new"
        Memory: <0x55bea8950fc0> Content:
```

**Comment by tsung-wei-huang** [comment] 2022-11-30 21:24
The error is not very informative. Is it possible for you to come up with an example that I can reproduce it on my end? For example, what is the taskflow structure you used in your workload, etc? 

Thanks!

**Comment by coder137** [comment] 2022-11-30 21:35
Hi @tsung-wei-huang,

This is the entire example

```cpp
#include "taskflow/taskflow.hpp"

// NOTE, Make sure all these includes are AFTER the system and header includes
#include "CppUTest/CommandLineTestRunner.h"
#include "CppUTest/MemoryLeakDetectorNewMacros.h"
#include "CppUTest/TestHarness.h"
#include "CppUTest/Utest.h"

TEST_GROUP(TaskStateTestGroup)
{
};

TEST(TaskStateTestGroup, TestTask) {
  tf::Taskflow taskflow;
  taskflow.emplace([]() { UT_PRINT("Hello World"); });

  // tf::Executor executor(1);
  // executor.run(taskflow).wait();
}

int main(int ac, char **av) {
  return CommandLineTestRunner::RunAllTests(ac, av);
}
```

**Comment by tsung-wei-huang** [comment] 2022-11-30 21:41
Doesn't seem to make any sense to me with a memory leak in this simple example. Would you please pate a complete report of the memory leak so I can take a look? Thanks.

**Comment by tsung-wei-huang** [comment] 2022-12-03 05:48
@coder137 Unfortunately, I am not able to reproduce the memory leak - which I believe is a false alarm. Starting from v3.3 the major change is the removal of the data race caused by TSAN. We no longer use any `thread_local` static storage. Unless you can kindly provide me a way to log into your machine for testing, I would encourage using v3.3 or onwards.

**Comment by coder137** [comment] 2022-12-04 14:52
Thank you for looking at this @tsung-wei-huang.
Performed additional tests with pure Taskflow + Valgrind examples and did not see any memory leak reported by Valgrind.

I have opened an issue with cpputest and will close this one.

**Comment by tsung-wei-huang** [comment] 2022-12-04 17:10
Thanks @coder137 , yes I didn't see any issues with valgrind. If you have any update from CppUTest, please let me know.

**Comment by coder137** [comment] 2022-12-10 19:08
Hi @tsung-wei-huang,

Had some progress on this issue 

The problem is outlined here: https://github.com/cpputest/cpputest/issues/1701#issuecomment-1343372268

And the solution for this is mentioned here: https://github.com/cpputest/cpputest/issues/1701#issuecomment-1344017048

Step 1: Manually manage the global `ObjectPool tf::node_pool`
Step 2: Make sure the allocation happens outside the TEST so that it is not tracked by the CppUTest Memory Leak plugin

Step 2 might not work for taskflow because the allocation inside the `ObjectPool::animate` function happens conditionally and in some cases, there might be more than 1 block allocated. In that case it would not be apparent how much the ObjectPool needs to allocate for a the entire test suite.

For Step 1, we could manage the static through a `tf::node_pool.init()` and `tf::node_pool.deinit()` in the setup and teardown APIs.
Or have a `clear` API to free all the allocated memory (the new blocks allocated etc)
However this would expose the init/deinit/clear APIs to the user.

What would you recommend in this situation?
Is there an existing way to manage/clear the memory allocated by the `ObjectPool<Node> node_pool`?

**Comment by tsung-wei-huang** [comment] 2022-12-11 02:49
@coder137 I can see the issue now. This is caused by the initialization orders among static objects. When `node_pool` is destroyed, it will automatically free all memory blocks ([see here](https://github.com/taskflow/taskflow/blob/6633a0919065f27b6697a8fb51ed36fbda8d384a/taskflow/utility/object_pool.hpp#L222)). However, since it is a static variable, when it gets destroyed may come after CppUTest, which is technically not a memory leak. Does this make sense to you?

**Comment by coder137** [comment] 2022-12-11 10:50
Yes, This is a known problem with CppUTest and the workarounds are as mentioned in option 1 and option 2.

CppUTest provides its own implementation/overrides of `new` and `delete` for its Memory Leak detector plugin to track allocations and deallocations.
Since `node_pool` allocates memory **during** the test but frees it **after** the program(test suite) ends, CppUTest flags that as a leak.

**Comment by tsung-wei-huang** [comment] 2023-01-04 19:35
@coder137 I do not think this is a leak problem but a design issue of CppUTest - which cannot handle static object like the `node_pool` in Taskflow. As far as I know, I have not seen any memory leak (reported by Valgrind) so far for Taskflow. So I will close this issue for now.

**Closed by tsung-wei-huang** 2023-01-04 19:35 UTC

**Comment by coder137** [comment] 2023-01-05 01:02
Hi @tsung-wei-huang ,

Yes this is a CppUTest limitation.

For a workaround is there a way I can manually clear the allocated memory in `node_pool`?

Or manually init/deinit the `node_pool`?
