### ISSUE TITLE
Exception handling for dispatch()

### ISSUE THREAD

**Issue by robinchrist** [taskflow/taskflow#72] opened 2019-03-25 10:33 UTC
I was running into issues where my application crashed with `std::terminate()`.
After some debugging I found out that in one task an exception is thrown.
I switched from `silent_dispatch()` to `dispatch()` and thought that I could catch these exceptions with the `shared_future` being returned from `dispatch`... However, this is not the case.
I assume that `std::terminate` is called because the worker threads are running in a detached state (aren`t they?)...

Do you think it's possible to add exception handling, at least for `dispatch`?
I'm not familiar enough with the internals of Taskflow (yet) to prepare code...

**Comment by tsung-wei-huang** [comment] 2019-03-25 15:43
Hi @robinchrist , in taskflow we do not explicitly handle exception but leave it to users. This is because everything happens in the multi-threaded environment and there could be more than one exception at one time. Even though we propagate the exception to the moment you call `get` on a `future` object, it is very difficult to keep track of the flow correctly. I suggest you add a try-catch block in the callback.

Hope this helps.

**Comment by robinchrist** [comment] 2019-03-25 15:52
@tsung-wei-huang 
My suggestion would be a special future with a built-in exception queue where all thrown exceptions are stored. 
Exception-safe dispatch could of course be optional if there's a speed-penalty...
The only thing I'm currently not sure about is what happens to the graph if an exception is thrown and caught... One option would be to execute as many tasks as possible or alternatively abort the execution of the graph ASAP

**Comment by tsung-wei-huang** [comment] 2019-03-26 03:18
Yes, I have thought about it but it requires every task to synchronize at the queue in order to insert multiple exception pointers or related data structures. This can introduce a non-negligible overhead.

**Comment by robinchrist** [comment] 2019-03-26 04:25
Basically you are right, but
- We could use a lock-free queue to reduce the overhead
- Our expectation is that no exceptions occur 99% of the time. If no exception is inserted, there's no overhead (waiting for the queue, etc.)

**Comment by KingDuckZ** [comment] 2019-04-24 15:31
I just wasted a few hours trying to figure out where my bug was as I thought taskflow would propagate exceptions correctly...

I've reduced my code to my_pool.silent_emplace([]() { throw std::runtime_error("lol"); }); and this is enough to reproduce the problem.
My use case is that I have multiple tasks producing parts of video frames. The first task to complete the last part of a frame will (through std::call_once) initialise some ffmpeg objects before finally sending the frame on to the codec. My issue is that I throw an exception when the ffmpeg initialisation fails and I'm unable to handle that exception gracefully in my try/catch block in main().
What should happen ideally is that upon exception no new tasks will be started. Pending tasks should complete (my tasks can handle the case where ffmpeg has not been initalised correctly) and program should quit as soon as possible. In fact it wouldn't make any sense to just keep going since if ffmpeg is not ready then all the work done by all the remaining tasks will just be thrown away as the frames get discarded without being saved to the disk.

Is there any way to achieve this?

**Comment by robinchrist** [comment] 2019-04-24 23:56
@KingDuckZ My suggestion is that you build your own exception handling ecosystem in the meantime.
As far as I understand, the problem is that the taskflow threadpool threads are running in a detached state, that means all uncaught exceptions immediately call std::terminate.
Wrap your task in a try/catch, pass the exception to a future and after the task has finished, check this future for an exception.

**Comment by KingDuckZ** [comment] 2019-04-25 09:50
Hi @robinchrist, I think I can easily do that thanks for the suggestion. What I don't understand tho is how can I stop cpp-taskflow after I catch the first exception? The main thread will be stuck on the call to wait_for_all()

**Comment by robinchrist** [comment] 2019-04-25 09:52
You could use an atomic bool which is shared across all tasks and check this atomic regularly.
If you check the atomic at the beginning of every task and return immediately, the rest of the taskflow should be completed in next to no time

**Comment by KingDuckZ** [comment] 2019-04-25 09:59
Ok... but lol that's ugly :D Better than crashing, but please add proper exception handling! :)

**Comment by emmenlau** [comment] 2021-09-21 12:30
I actually think that this issue should be re-opened and reconsidered. The reason is that Taskflow would be in a very good situation to help the user with exception handling. For example, Taskflow could have a higher-level wrapper over `tf::Taskflow`, something like `tf::CheckedTaskflow`, that implements the above-mentioned logic. This would be relatively little work on Taskflow side, with an over-proportional gain for users. Most users wold implement exception handling in a very similar way, and having this implemented (safe and sound) in a centralized place is much better.

**Comment by tsung-wei-huang** [comment] 2021-09-21 15:18
@emmenlau thanks for the very insightful opinion. The biggest challenge here we may end up with multiple exceptions concurrently. Of course, we can store all of them or just one of them (order is never guaranteed due to multithreading). At the end, we can forward the exception to `tf::Future` returned from `tf::Executor::run`. What would you suggest?

I am very welcome for any contributions/pulls like this.

**Comment by emmenlau** [comment] 2021-09-21 17:56
Dear @tsung-wei-huang , thanks for your consideration! Below more:

> @emmenlau thanks for the very insightful opinion. The biggest challenge here we may end up with multiple exceptions concurrently. Of course, we can store all of them or just one of them (order is never guaranteed due to multithreading). At the end, we can forward the exception to `tf::Future` returned from `tf::Executor::run`. What would you suggest?

In my humble opinion, I would only deal with the first exception. This will have a number of benefits:
 - It is very easy to store and rethrow this single first exception. Just use the standard mechanisms like re-throw or std::exception_ptr, no need for anything fancy.
 - It will be very easy for the user to deal with the exception. Taskflow can give the guarantee that there is either no exception, or the single first exception in its original type.
 - I do not think it is very helpful for the user to get a list of exceptions. As soon as Taskflow receives the first exception, I think it will be highly beneficial that Taskflow will do its best to not schedule any more work. Therefore, the list of exceptions will likely not be complete. I do not see the benefit of an incomplete list of exceptions over the single first one.

Forwarding the exception to `tf::Future` sounds like a very good idea indeed.

**Comment by milianw** [comment] 2021-11-26 09:34
I would also be very interesting in seeing this come to fruition.

But to make things a bit more complicated, let me add an issue we are currently facing with OpenMP, where I don't see a solution to. If tf could handle this better, it would be a great boon and make porting so much more worthwhile for us:

In our code base, we operate a lot on memory mapped regions. When a mapped buffer is accessed and a page fault occurs that cannot be handled, then the system will raise a SIGBUS (on *nix), or do some special kind of exception unwinding (on windows). Basically see: https://www.sublimetext.com/blog/articles/use-mmap-with-care

Maybe the solution to both would be for taskflow to add a customization point, such that one could centrally install custom exception handler code before any task is run. Meaning: TF could just ignore exceptions as it does currently, but if someone wants to handle them, one could do it. Something like:

```
tf::Executor executor;

// dunno if this should be on the flow or on the executor?
executor.set_task_wrapper([](auto task) {
    // here we could setup exception handling or sigbus handling
    // then we can run the task
    task();
    // and finally try to recover and/or store the exception somewhere if we would like
});
```

**Comment by dinesh-10** [comment] 2022-11-18 13:21
Hi, 

Is there any plan when this will be available. ? 

I spent many hours in debugging an exception with taskflow. 
The difference we get with taskflow compared to std is, the behavior of async. Where std::async doesn't crash on exception and returns the exception to main using future's get() and Executor::async crashes as soon as an exception occurs inside the subroutine. Which makes porting to taskflow difficult. 

Forwarding the exception using tf::Future is a great idea. and it will resemble the library implementation.

**Comment by tsung-wei-huang** [comment] 2022-11-19 17:39
Do you mean forwarding an exception, if any, to `tf::Future::get()` only for `tf::Executor::async` tasks?

**Comment by bradphelan** [comment] 2023-08-30 11:14
Yes he means that exceptions within tf::Executor::async are not forwarded to the future. This doesn't require any queue or locking to implement so the reason for not doing it is not clear. See https://github.com/taskflow/taskflow/issues/499 for attempts at work arounds. One of the main issues is that promises are not copyable but the function passed to tf::Executor::async is copied. This forces the user who wants to handle exceptions into passing a promise into a shared_ptr

**Comment by tsung-wei-huang** [comment] 2023-09-27 23:57
@bradphelan @milianw @emmenlau @KingDuckZ @robinchrist @dinesh-10 ,

the exception support is up in the current master/dev branch. Examples can be found [here](https://taskflow.github.io/taskflow/ExceptionHandling.html). Please share any feedback. This support will be part of release v3.7. 

Thank you for your contributions!

**Closed by tsung-wei-huang** 2023-09-27 23:57 UTC

**Comment by fran6co** [comment] 2023-10-03 11:14
@tsung-wei-huang how does the new exception support work inside pipelines? They seem to be getting ignored by taskflow

**Comment by bradphelan** [comment] 2023-10-03 12:12
> @bradphelan @milianw @emmenlau @KingDuckZ @robinchrist @dinesh-10 ,
> 
> the exception support is up in the current master/dev branch. Examples can be found [here](https://taskflow.github.io/taskflow/ExceptionHandling.html). Please share any feedback. This support will be part of release v3.7.
> 
> Thank you for your contributions!

Sorry but the new exception support does not work for common use cases. It only works on Executor.run but not Executor::corun as corun does not return a future. A typical use case is the following.

```c++
tf::Taskflow taskflow;
taskflow.for_each_index(0, 10, [](int i){
   if (i==5){
       throw std::runtime_error("foo");
  }
});
try{
    executor.co_run(taskflow);
}catch(std::runtime_error & e){
    std::cout << e.what();
}
```

``executor.run`` is only ever called once at the top level of the program and if exceptions are surfaced there it is too late to handle them.

**Comment by bradphelan** [comment] 2023-10-04 06:41
Thats sounds awesome.  Thankyou ❤

**Comment by yurivict** [comment] 2024-02-09 04:07
@tsung-wei-huang 

The current behavior is that a thrown exception causes this task to stop and hang that way.
std::terminate isn't called.
Is this expected or is this a bug?

-------------------------------------

Do you know when 3.7 will be released?
