### ISSUE TITLE
Variable naming issue (N)

### ISSUE THREAD

**Issue by malcolmhartley** [taskflow/taskflow#331] opened 2021-07-20 20:45 UTC
While running a for_each task I had an issue with calling member functions from an integer vector named (N). This vector (N) was a member of an object instance of a class which served the purpose of providing shared memory between various threads. It should be noted that the main Taskflow was contained in a function belonging to this class. 

The issue is that using N.at(i) would cause the compiler to exit with an error. The error was something along the lines of "tf::Taskflow has no member function at()". 

The solution was to name the vector something other than "N". However, I am still unclear as to the cause of the error.

Version Info:
 - OS: macOS Big Sur
 - Taskflow v3.0

**Comment by tsung-wei-huang** [comment] 2021-07-20 23:10
I am a bit confused because I didn't see any issues of having a vector of name "N". Would you please paste your code for me to reproduce the error?

**Comment by malcolmhartley** [comment] 2021-07-20 23:12
Sure, I will have to reproduce it but it’s no problem I will get back to you in a bit.

Best regards,

Malcolm Hartley-Urquhart

**Comment by tsung-wei-huang** [comment] 2021-08-18 21:37
Is this issue still there? I close it for now but feel free to reopen it.

**Closed by tsung-wei-huang** 2021-08-18 21:37 UTC

**Comment by malcolmhartley** [comment] 2021-08-19 14:03
I haven’t noticed any further issues so I think you can close it.

Best regards,

Malcolm Hartley-Urquhart
